[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# New/Edited functions used for all sorts of things
[[patches]]
[patches.copy]
target = "main.lua"
position = "append"
sources = [
	"misc/inject_functions.lua"
]

# Add a beat anim to the main menu
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "replace_card.states.visible = false"
position = "before"
payload = "rh_beat_anim(replace_card)"
match_indent = true

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''
                    card:start_materialize()
                    self.title_top:emplace(card)'''
position = "after"
payload = "rh_beat_anim(card)"
match_indent = true
